name: Deploy FastAPI Backend to Azure Web App

on:
  push:
    branches:
      - master  # Changed from main to master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r new_backend/requirements.txt

      - name: Archive backend for deployment
        run: |
          cd new_backend
          zip -r ../backend.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: smart-email-backend
          slot-name: 'production'
          package: ./backend.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}